Script improvements, change in format a bit

diff --git a/scripts/all_files_subtasks b/scripts/all_files_subtasks
--- a/scripts/all_files_subtasks
+++ b/scripts/all_files_subtasks
@@ -2,17 +2,37 @@
 
 set -e
 
+# check if some params are missing
+globpattern="$1"
+if [[ -z "$globpattern" ]]; then
+    >&2 echo "ERROR (all_files_subtasks): The first argument must contain a pattern matching the input files (enclosed in quotes)."  
+    exit 1
+fi
+
+if [[ -z "${@:2}" ]]; then
+    >&2 echo "ERROR (all_files_subtasks): The rest of the arguments must contain the command for the subtask detector."  
+    exit 1
+fi
+
+total=""
 while IFS= read -rd '' file; do
-    y=`"${@:2}" < $file`
+    y=$("${@:2}" < $file)
     if [ -z "$y" ]; then
-        printf "ERROR!!!! %s doesn't appear in any subtask\n" $file
+        echo "ERROR (all_files_subtasks): $file doesn't appear in any subtask"
         exit 1
     fi
     printf "%30s appears in the following subtasks: " $file
-    for sub in $y; do
+    for sub in $(echo $y | xargs -n1 | sort -V | uniq); do
         printf "%s " $sub
     done
     echo
-done < <(find $1 -print0 | sort -z -V)
+    total="$total $y"
+done < <(find . -wholename "./$globpattern" -print0 | sort -z -V)
 
-echo SUBTASKS OK
+printf "Distinct subtasks found:"
+for sub in $(echo $total | xargs -n1 | sort -V | uniq); do
+    printf " %s" $sub
+done
+echo
+
+echo "Subtasks OK"
diff --git a/scripts/convert_to_hackerrank b/scripts/convert_to_hackerrank
--- a/scripts/convert_to_hackerrank
+++ b/scripts/convert_to_hackerrank
@@ -2,19 +2,25 @@
 
 set -e
 
-mkdir -p input
-mkdir -p output  
+# check if some params are missing
+IFS= tests="$1"
+if [[ -z "$tests" ]]; then
+    >&2 echo "ERROR (convert_to_hackerrank): The first argument must be the tests folder of the Polygon package."
+    exit 1
+fi
+
+mkdir -p input output  
 for x in input/input*.txt output/output*.txt; do
     [ -e $x ] && rm $x
 done
 
 idx=0
-if ! [ -z $1 ]; then
+if [[ -n "$tests" ]]; then
     while IFS= read -rd '' src; do
         cp $src $(printf "input/input%02d.txt" $idx)       # input file 
         cp $src.a $(printf "output/output%02d.txt" $idx)   # output file 
         idx=$((idx+1))
-    done < <(find $1/* -print0 | grep -z -v '\.a$' | sort -z -V)
+    done < <(find $tests -type f -name '*' -print0 | grep -z -v '\.a$' | sort -z -V)
 fi
 
-echo Converted $idx files
+echo "Converted $idx files"
diff --git a/scripts/direct_to_hackerrank b/scripts/direct_to_hackerrank
--- a/scripts/direct_to_hackerrank
+++ b/scripts/direct_to_hackerrank
@@ -2,33 +2,45 @@
 
 set -e
 
-script_name=$0
-__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+testset="$1"
+if [[ -z "$testset" ]]; then
+    >&2 echo "ERROR (direct_to_hackerrank): The first argument must be the location of the testset script."  
+    exit 1
+fi
 
-# prepare hackerrank folders
-echo PREPARING FOLDERS
-mkdir -p input
-mkdir -p output  
+if [[ -z "$2" ]]; then
+    >&2 echo "ERROR (direct_to_hackerrank): The second argument must be the validator command."  
+    exit 1
+fi
+
+if [[ -z "$3" ]]; then
+    >&2 echo "ERROR (direct_to_hackerrank): The thirds argument must be the solution command."  
+    exit 1
+fi
+
+echo "PREPARING FOLDERS"
+current="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+mkdir -p input output  
 for x in input/input*.txt output/output*.txt; do
     [ -e $x ] && rm $x
 done
 
 # create data set
-echo GENERATING INPUT FILES
-/usr/bin/python2 $__dir/_compile_testsets_to_bash.py $1 "$2" | bash
-echo GENERATED $(find input/input*.txt | wc -l) FILES
+echo "GENERATING INPUT FILES"
+/usr/bin/python2 $current/_compile_testsets_to_bash.py "$testset" "$2" | bash
+echo "GENERATED $(find input/input*.txt | wc -l) FILES"
 
 # detect subtasks
-subs=${@:4}
-if [ -z "$subs" ]; then
-    echo NO SUBTASKS LIST... NOT DETECTING SUBTASKS
+subs="$4"
+if [[ -z "$subs" ]]; then
+    echo "NO SUBTASKS LIST... NOT DETECTING SUBTASKS"
 else
-    echo DETECTING SUBTASKS
-    $__dir/all_files_subtasks "input/input*.txt" $__dir/subtasks_from_validator "$2" $subs
+    echo "DETECTING SUBTASKS"
+    $current/all_files_subtasks "input/input*.txt" $current/subtasks_from_validator $subs "$2"
 fi
 
 # generate output
-echo GENERATING OUTPUT FILES
-$__dir/hr genout $3
+echo "GENERATING OUTPUT FILES"
+$current/hr genout "$3"
 
-echo DONE
+echo "DONE. ALL OK"
diff --git a/scripts/subtasks_from_validator b/scripts/subtasks_from_validator
--- a/scripts/subtasks_from_validator
+++ b/scripts/subtasks_from_validator
@@ -2,18 +2,29 @@
 
 set -e
 
-BASURA=basura_delete_later_once_scripts_finish_running
+# check if some params are missing
+subs="$1"
+if [[ -z "$subs" ]]; then
+    >&2 echo "ERROR (subtasks_from_validator): The first argument must be the subtask list, comma separated."
+    exit 1
+fi
 
+if [[ -z "${@:2}" ]]; then
+    >&2 echo "ERROR (subtasks_from_validator): The rest of the arguments must be the validator command."
+    exit 1
+fi
+
+BASURA=basura_delete_later_once_scripts_finish_running
 cat > $BASURA # store input to temp file
 
-for x in "${@:2}"; do
-    if $1 $x < $BASURA 2> ${BASURA}2; then
-        echo $x
+for sub in $(echo "$subs" | sed "s/,/ /g"); do
+    if ${@:2} $sub < $BASURA > ${BASURA}_vout 2> ${BASURA}_verr; then
+        echo $sub
     fi
 done
 
 
 # remove kalat
-for x in $BASURA ${BASURA}2; do
+for x in ${BASURA}{,_v{out,err}}; do
     [ -e $x ] && rm $x
 done
